### ISSUE TITLE
As a person who wants to graduate, I want the optional option to list my midterm, quizzes, and final time to let my friends know when not to disturb me.

### ISSUE THREAD

**Issue by XiangweiChen** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#6]
Takes in input and prints the input after clicking the "Add" button in Exams
### Acceptance Test:
 
- [x] Submit button on add/edit page only submits when the input field isn't empty.

- [x]  Clicking the submit field with inputs will show what you inputted in the field

- [x]  Submit button does not work on invalid year (not 4 digits, not valid characters, before 2020)

- [x]  Submit button does not work on invalid date (not 2 digits, not valid characters, before 30 or 31)

- [x] Submit button does not work on invalid month (not 2 digits, not valid characters, between 1 and 12)

- [x] On the edit page, the user can edit a current exam with a new name, a new day or a new year correctly, but there exists a bug where the new month can't be store for now

**Comment by JerryLee0323** [comment]
Acceptance Test:

1. On the home page, click the button where it says "Exams" and it'll direct you to the exam page.
2. On the exam page, it will list your exams and have the edit and add button.
3. The add button will direct you to a different page where you can add an exam and submit it.
4. The edit button will direct you to a different page where you can edit an existing exam if there are exams to edit. Otherwise, do nothing
